basePath: /
definitions:
  core.Course:
    properties:
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      nameFolder:
        description: DELETE
        type: string
    type: object
  core.Lesson:
    properties:
      description:
        type: string
      id:
        type: integer
      moduleID:
        type: integer
      name:
        type: string
      nameFile:
        description: DELETE
        type: string
      orderID:
        type: integer
    type: object
  core.ModLes:
    properties:
      courseID:
        type: integer
      description:
        type: string
      id:
        type: integer
      lessons:
        items:
          $ref: '#/definitions/core.Lesson'
        type: array
      name:
        type: string
      nameFolder:
        description: DELETE
        type: string
      orderID:
        type: integer
    type: object
  core.Tokens:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
  handler.AddCourse:
    properties:
      description:
        type: string
      name:
        type: string
    type: object
  handler.EdModule:
    properties:
      description:
        type: string
      name:
        type: string
      orderid:
        type: integer
    type: object
  handler.Refresh:
    properties:
      refresh_token:
        type: string
    type: object
  handler.SignInput:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: EptaNit Super Site
  title: eptanit.com
  version: "2.71"
paths:
  /adm/course/{id}:
    put:
      consumes:
      - application/json
      description: Edit course by ID
      operationId: EditCourse
      parameters:
      - description: Идентификатор курса для обновления
        in: path
        name: id
        required: true
        type: integer
      - description: Edit Course
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.AddCourse'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: error
          schema:
            type: string
        "500":
          description: error
          schema:
            type: string
        default:
          description: error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: EditCourse
      tags:
      - course
  /adm/module/{id}:
    put:
      consumes:
      - application/json
      description: Edit module by ID
      operationId: EditModule
      parameters:
      - description: Module ID
        in: path
        name: id
        required: true
        type: integer
      - description: Edit Module (OrderId starts with one)
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.EdModule'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: error
          schema:
            type: string
        default:
          description: error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: EditModule
      tags:
      - module
  /course/{id}:
    get:
      consumes:
      - application/json
      description: Get courses by ID with all modules&lessons
      operationId: GetCourse
      parameters:
      - description: Course ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/core.Course'
        "400":
          description: error
          schema:
            type: string
        "500":
          description: error
          schema:
            type: string
        default:
          description: error
          schema:
            type: string
      summary: GetCourse
      tags:
      - course
  /course/getall:
    get:
      consumes:
      - application/json
      description: Get all courses
      operationId: GetAllCourses
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/core.Course'
        "500":
          description: error
          schema:
            type: string
        default:
          description: error
          schema:
            type: string
      summary: All courses
      tags:
      - course
  /course/search/{name}:
    get:
      consumes:
      - application/json
      description: Get courses by name
      operationId: GetCourseByName
      parameters:
      - description: Имя курса для поиска
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/core.Course'
        "500":
          description: error
          schema:
            type: string
        default:
          description: error
          schema:
            type: string
      summary: Searching Courses
      tags:
      - course
  /module/{id}:
    get:
      consumes:
      - application/json
      description: Get module by ID
      operationId: GetModule
      parameters:
      - description: Module ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/core.ModLes'
        "400":
          description: error
          schema:
            type: string
        "500":
          description: error
          schema:
            type: string
        default:
          description: error
          schema:
            type: string
      summary: GetModule
      tags:
      - module
  /refresh:
    post:
      consumes:
      - application/json
      description: Refresh access token for Admin
      operationId: refresh
      parameters:
      - description: Refresh token
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.Refresh'
      produces:
      - application/json
      responses:
        "200":
          description: token
          schema:
            type: string
        "500":
          description: error
          schema:
            type: string
        default:
          description: error
          schema:
            type: string
      summary: Refresh Access Token
      tags:
      - auth
  /sign-in:
    post:
      consumes:
      - application/json
      description: login for admins
      operationId: login
      parameters:
      - description: admin info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.SignInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/core.Tokens'
        "500":
          description: error
          schema:
            type: string
        default:
          description: error
          schema:
            type: string
      summary: SignInAdmin
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
