basePath: /
host: localhost:8000
info:
  contact: {}
  description: EptaNit Super Site
  title: EptaNit dot COM <3
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
